### ISSUE TITLE
Individual probabilities for HG events

### ISSUE THREAD

**Issue by CampbellCrowley** [CampbellCrowley/SpikeyBot-Discord#29]
Give the "Default" events a global probability of happening, but each "Custom" event will have it's own individual probability of being chosen.

Potential problems:
- This poses the potential issue of increasing performance requirements to sift through all probability values of the events.
- This gives the user another way to put the simulation in a place where it may be impossible to find valid events to choose. More edge cases will appear.

**Comment by esda01** [comment]
If game performance is an issue, perhaps you could have a simple mode and an advanced mode. That way people who don't feel the need to have all the bells and whistles aren't causing the bot to lag as much!

**Comment by CampbellCrowley** [comment]
I'd prefer to use one system across all "event picking" since that's the easiest thing to break, breaking it into 2 systems might make it harder to continuously support.

The difference between an advanced and simple mode would realistically just be a change in the GUI.

I don't think the performance will be a huge issue, it's just a possibility of being a problem that I need to remember to consider when I'm implementing it.

**Comment by CampbellCrowley** [comment]
`customEventWeight` option solves this well enough. Each individual event does not need to have a custom weight in most cases, since users generally preferred to have their own custom events weighted higher than the default ones.

This can be reopened if there is demand for individually applied weights again.
