### ISSUE TITLE
HG Included players not persisting properly across game start

### ISSUE THREAD

**Issue by CampbellCrowley** [CampbellCrowley/SpikeyBot-Discord#80]
HG players are sometimes excluded from the game once it starts even though `hg include all` was previously ran.

**Comment by 9382** [comment]
I'd like to add this only occurs when the previous round is bugged and requires a force stop or malfunctions in any significant way - and its only a select amount of users (11) and the exact same every time

**Comment by CampbellCrowley** [comment]
Possibly an issue with file parsing. Issue seems to occur after a large delay (~1 hour).

**Comment by CampbellCrowley** [comment]
9601e94 Closes this
